//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traversal_Rezervasyon.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _MemberLayout {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _MemberLayout() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Traversal_Rezervasyon.Resources._MemberLayout", typeof(_MemberLayout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Profilim {
            get {
                return ResourceManager.GetString("Profilim", resourceCulture);
            }
        }
        
        internal static string Aktif_Rezervasyonlar {
            get {
                return ResourceManager.GetString("Aktif Rezervasyonlar", resourceCulture);
            }
        }
        
        internal static string Geçmiş_Rezervasyonlar {
            get {
                return ResourceManager.GetString("Geçmiş Rezervasyonlar", resourceCulture);
            }
        }
        
        internal static string Onay_Bekleyen_Rezervasyonlar {
            get {
                return ResourceManager.GetString("Onay Bekleyen Rezervasyonlar", resourceCulture);
            }
        }
        
        internal static string Yeni_Rezervasyonlar {
            get {
                return ResourceManager.GetString("Yeni Rezervasyonlar", resourceCulture);
            }
        }
        
        internal static string Yorumlarım {
            get {
                return ResourceManager.GetString("Yorumlarım", resourceCulture);
            }
        }
        
        internal static string Tur_Rotaları {
            get {
                return ResourceManager.GetString("Tur Rotaları", resourceCulture);
            }
        }
        
        internal static string Son_Rotalar {
            get {
                return ResourceManager.GetString("Son Rotalar", resourceCulture);
            }
        }
        
        internal static string Siteye_Git {
            get {
                return ResourceManager.GetString("Siteye Git", resourceCulture);
            }
        }
        
        internal static string Çıkış_Yap {
            get {
                return ResourceManager.GetString("Çıkış Yap", resourceCulture);
            }
        }
    }
}
